import Mathlib.Probability.Independence.Conditional
import Mathlib.Probability.ProbabilityMassFunction.Basic

/-! ## Independent product of probability measures -/

open ProbabilityTheory MeasureTheory

alias MeasureTheory.MeasureSpace.σAlg := MeasureSpace.toMeasurableSpace
alias MeasureTheory.MeasureSpace.μ := MeasureSpace.volume

variable {Ω : Type*}

/-- We define `(ℱ, μ) ≤ (𝒢, ν)` if `ℱ ≤ 𝒢` and `μ` is the restriction of `ν` to `ℱ` -/
instance : Preorder (MeasureSpace Ω) where
  -- TODO: double-check if we are supposed to use `map` or `comap`
  le m₁ m₂ := (m₁.σAlg ≤ m₂.σAlg) ∧ m₁.μ = (@Measure.map _ _ m₂.σAlg m₁.σAlg id m₂.μ)
  le_refl m := by simp only [LE.le, imp_self, implies_true, Measure.map_id, and_self]
  le_trans := by
    rintro ⟨ℱ₁, μ₁⟩ ⟨ℱ₂, μ₂⟩ ⟨ℱ₃, μ₃⟩ ⟨hℱ₁₂, hμ₁₂⟩ ⟨hℱ₂₃, hμ₂₃⟩
    simp_all
    refine ⟨le_trans hℱ₁₂ hℱ₂₃, ?_⟩
    · rw [Measure.map_map] <;> aesop

/-- The sum of two measurable spaces on the same space `Ω` is the measurable space generated by the
  union of the two spaces -/
def MeasurableSpace.sum (m₁ : MeasurableSpace Ω) (m₂ : MeasurableSpace Ω) : MeasurableSpace Ω :=
  MeasurableSpace.generateFrom (MeasurableSet[m₁] ∪ MeasurableSet[m₂])

namespace ProbabilityTheory

/-- A probability space is a `MeasureSpace` where the measure is a probability measure (i.e. has
  total measure `1`) -/
class ProbabilitySpace (Ω : Type*) extends MeasureSpace Ω where
  [is_prob : IsProbabilityMeasure volume]

def ProbabilitySpace.σAlg [P : ProbabilitySpace Ω] : MeasurableSpace Ω :=
  ProbabilitySpace.toMeasureSpace.toMeasurableSpace
def ProbabilitySpace.μ [P : ProbabilitySpace Ω] : Measure[P.σAlg] Ω :=
  ProbabilitySpace.toMeasureSpace.volume

/-- A probability mass function, under some measurable space, induces a probability space -/
noncomputable def ProbabilitySpace.ofPMF [MeasurableSpace Ω] (μ : PMF Ω) : ProbabilitySpace Ω :=
  { toMeasurableSpace := inferInstance,
    volume := μ.toMeasure,
    is_prob := PMF.toMeasure.isProbabilityMeasure μ }

@[simp]
instance ProbabilitySpace.instProbabilityMeasure [P : ProbabilitySpace Ω] :
    IsProbabilityMeasure (P.μ) :=
  ProbabilitySpace.is_prob

@[simp]
lemma ProbabilitySpace.σAlg_apply [P : ProbabilitySpace Ω] :
    P.σAlg = P.toMeasureSpace.toMeasurableSpace := rfl
@[simp]
lemma ProbabilitySpace.μ_apply [P : ProbabilitySpace Ω] :
    P.μ = P.toMeasureSpace.volume := rfl

/-- We define `(ℱ, μ) ≤ (𝒢, ν)` if `ℱ ≤ 𝒢` and `μ` is the restriction of `ν` to `ℱ` -/
instance : Preorder (ProbabilitySpace Ω) where
  le m₁ m₂ := (m₁.σAlg ≤ m₂.σAlg) ∧ m₁.μ = (@Measure.map _ _ m₂.σAlg m₁.σAlg id m₂.μ)
  le_refl m := by simp only [LE.le, imp_self, implies_true, Measure.map_id, and_self]
  le_trans := by
    rintro ⟨ℱ₁, μ₁, _⟩ ⟨ℱ₂, μ₂, _⟩ ⟨ℱ₃, μ₃, _⟩ ⟨hℱ₁₂, hμ₁₂⟩ ⟨hℱ₂₃, hμ₂₃⟩
    simp_all
    refine ⟨le_trans hℱ₁₂ hℱ₂₃, ?_⟩
    · rw [Measure.map_map] <;> aesop

end ProbabilityTheory

/-! ### Canonical unit probability space

We provide `One (ProbabilitySpace Ω)` as the Dirac measure at a chosen point,
requiring `[Nonempty Ω]`. -/

noncomputable section

variable {Ω : Type*}

instance [inst : Nonempty Ω] : One (ProbabilityTheory.ProbabilitySpace Ω) where
  one := @ProbabilityTheory.ProbabilitySpace.mk Ω
    (@MeasureTheory.MeasureSpace.mk Ω ⊥
      (@MeasureTheory.Measure.dirac _ ⊥ (Classical.choice inst)))
    (by constructor; simp [MeasureTheory.Measure.dirac])

end

section IndependentProduct

variable {m₁ : MeasurableSpace Ω} {m₂ : MeasurableSpace Ω}

/-- An independent product of measures `μ₁` and `μ₂` (on measurable spaces `m₁` and `m₂`,
    respectively) is a measure `μ` on the sum of `m₁` and `m₂` that satisfies the product formula -/
@[ext]
class Measure.IndependentProduct (μ₁ : Measure[m₁] Ω) (μ₂ : Measure[m₂] Ω) where
  μ : Measure[MeasurableSpace.sum m₁ m₂] Ω
  inter_eq_prod {X Y} (hX : MeasurableSet[m₁] X) (hY : MeasurableSet[m₂] Y) :
    μ (X ∩ Y) = μ₁ X * μ₂ Y

/-- The independent product of two measures is unique, if it exists -/
instance {μ₁ : Measure[m₁] Ω} {μ₂ : Measure[m₂] Ω} : Subsingleton (Measure.IndependentProduct μ₁ μ₂) := by
  constructor
  intro ⟨μ, hμ⟩ ⟨μ', hμ'⟩
  ext
  simp
  sorry
  -- To prove this, [Li et al. 2023] requires the Dynkin π-λ theorem, which is
  -- `MeasurableSpace.induction_on_inter`.

#check IsPiSystem
#check MeasurableSpace.induction_on_inter

noncomputable section

/-- The partial operation of independent product on `MeasureSpace`s, when it exists -/
def MeasureTheory.MeasureSpace.indepProduct (m₁ : MeasureSpace Ω) (m₂ : MeasureSpace Ω) : Option (MeasureSpace Ω) := by
  classical
  by_cases h : Nonempty (Measure.IndependentProduct m₁.2 m₂.2)
  · exact some (@MeasureSpace.mk Ω (m₁.1.sum m₂.1) (Classical.choice h).μ)
  · exact none

/-- The partial operation of independent product on `ProbabilitySpace`s, when it exists -/
def ProbabilityTheory.ProbabilitySpace.indepProduct (m₁ : ProbabilitySpace Ω) (m₂ : ProbabilitySpace Ω) : Option (ProbabilitySpace Ω) := by
  classical
  -- Re-express in terms of existence of an independent product witness to build the space and certify probability.
  by_cases h : Nonempty (Measure.IndependentProduct m₁.μ m₂.μ)
  · -- Build the combined `MeasureSpace` from the witness and prove it's a `ProbabilitySpace` by μ(univ)=1.
    refine some
      { toMeasureSpace := @MeasureSpace.mk Ω (m₁.σAlg.sum m₂.σAlg) (Classical.choice h).μ
        is_prob := by
          -- `μ(univ) = 1` follows from the rectangle formula with X=univ, Y=univ.
          have hX : MeasurableSet[m₁.σAlg] (Set.univ) := by simp
          have hY : MeasurableSet[m₂.σAlg] (Set.univ) := by simp
          have hμ : (Classical.choice h).μ (Set.univ) = m₁.μ Set.univ * m₂.μ Set.univ := by
            simpa [Set.univ_inter] using (Classical.choice h).inter_eq_prod (X := Set.univ) (Y := Set.univ) hX hY
          have hμ1 : m₁.μ Set.univ = 1 := by simpa using (inferInstance : IsProbabilityMeasure m₁.μ).measure_univ
          have hμ2 : m₂.μ Set.univ = 1 := by simpa using (inferInstance : IsProbabilityMeasure m₂.μ).measure_univ
          constructor
          rw [hμ1, hμ2] at hμ
          simp at hμ
          simpa only [σAlg_apply, μ_apply] using hμ }
  · -- No independent product witness exists at the measure level.
    exact none

end

end IndependentProduct

namespace ProbabilityTheory

namespace ProbabilitySpace

variable {Ω : Type*}

/-- Symmetry: independent product is commutative (API statement). -/
theorem indepProduct_comm (m₁ m₂ : ProbabilitySpace Ω) :
    indepProduct m₁ m₂ = indepProduct m₂ m₁ := by
  -- Proof via swapping factors and uniqueness of independent product.
  sorry

/-- Left unit: the unit probability space acts as a left identity for `indepProduct` (API).
Requires `[Nonempty Ω]` to use the canonical Dirac-on-a-point unit. -/
theorem indepProduct_one_left [Nonempty Ω] (m : ProbabilitySpace Ω) :
    indepProduct (1 : ProbabilitySpace Ω) m = some m := by
  -- Proof via rectangle formula on univ and uniqueness.
  sorry

/-- Right unit: the unit probability space acts as a right identity for `indepProduct` (API).
Requires `[Nonempty Ω]` to use the canonical Dirac-on-a-point unit. -/
theorem indepProduct_one_right [Nonempty Ω] (m : ProbabilitySpace Ω) :
    indepProduct m (1 : ProbabilitySpace Ω) = some m := by
  -- Proof via rectangle formula on univ and uniqueness.
  sorry

/-- Associativity: reassociating a triple independent product yields the same result (API). -/
theorem indepProduct_assoc (m₁ m₂ m₃ : ProbabilitySpace Ω) :
    (do let ab ← indepProduct m₁ m₂; indepProduct ab m₃) =
    (do let bc ← indepProduct m₂ m₃; indepProduct m₁ bc) := by
  -- Proof via measurable space isomorphism between (m₁ ⊕ m₂) ⊕ m₃ and m₁ ⊕ (m₂ ⊕ m₃)
  -- and uniqueness of independent products.
  sorry

end ProbabilitySpace

end ProbabilityTheory

#check MeasureSpace

#check MeasureTheory.Measure.IsComplete

/-- A set `s` is almost measurable with respect to a measure space `μ` if it is sandwiched between
  two measurable sets that have the same measure -/
def almostMeasurableSet [μ : MeasureSpace Ω] (s : Set Ω) :=
  ∃ t₁ t₂, MeasurableSet t₁ ∧ MeasurableSet t₂ ∧ t₁ ⊆ s ∧ s ⊆ t₂ ∧ μ.volume t₁ = μ.volume t₂

-- I think this is the same as `toMeasurable`, and also `almost measurable` functions in the paper
-- should coincide with the `AEMeasurable` class

#check AEMeasurable
