name = "iris"
srcDir = "./src/"
defaultTargets = ["Iris", "IrisTest"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.21.0"

[[lean_lib]]
name = "Iris"

[[lean_lib]]
name = "IrisTest"
globs = ["Iris.*"]
