name = "iris"
srcDir = "./src/"
defaultTargets = ["Iris", "IrisTest"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.24.0"

[[lean_lib]]
name = "Iris"
globs = ["Iris.*"]

[[lean_lib]]
name = "Bluebell"
globs = ["Bluebell.*"]

[[lean_lib]]
name = "IrisTest"
globs = ["Iris.*"]
